Algoritmo "FACCAT 19"
// Exercicio 19 FACCAT, Maior valor.
Var
// Seção de Declarações das variáveis 
   valor1, valor2: real

Inicio
   escreva("Digite o primeiro valor: ")
   leia(valor1)

   escreva("Digite o segundo valor: ")
   leia(valor2)

   se valor1 > valor2 então
      escreva("O maior valor é: ", valor1)
   senão
      escreva("O maior valor é: ", valor2)
   fimse


Fimalgoritmo