Algoritmo "FACCAT 20"
// Exercicio 20 FACCAT, Ordem crescente.
Var

 valor1, valor2: real
 
Inicio

   escreval("Digite o primeiro valor: ")
   leia(valor1)

   escreval("Digite o segundo valor: ")
   leia(valor2)

   se valor1 < valor2 então
      escreva("Os valores em ordem crescente são: ", valor1, " e ", valor2)
   senão
      escreva("Os valores em ordem crescente são: ", valor2, " e ", valor1)
   fimse


Fimalgoritmo