Algoritmo "Faccat 06"
// Exercicio 06 FACCAT
//Area retangulo
Var
// Seção de Declarações das variáveis 
       base, altura, area: real

Inicio

   escreva("Digite a base do retângulo: ")
   leia(base)

   escreva("Digite a altura do retângulo: ")
   leia(altura)

   // Calcular a área do retângulo
   area <- base * altura

   // Escrever a área
   escreva("A área do retângulo é: ", area)

Fimalgoritmo